[package]
name = "baby_fuzzer_with_custom_executor"
version = "0.1.0"
edition = "2024"

[dependencies]
libafl = "0.15.2"
libafl_bolts = "0.15.2"

[profile.dev]
panic = "abort"

[features]
tui = []
bloom_input_filter = []
