[package]
name = "fuzzing_c_code_with_fork_executor"
version = "0.1.0"
edition = "2024"

[dependencies]
libafl = "0.15.2"
libafl_bolts = "0.15.2"
libc = "0.2.172"

[build-dependencies]
cc = "1.0"

[features]
tui = []
